### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by fableman73** [gurre/php-personnummer#1]
ERROR:
root@biblan:/var/www/html# php hhh.php 
PHP Notice:  Undefined index: 811115-1401 in /var/www/html/hhh.php on line 3

Trying example code: 
root@biblan:/var/www/html# cat hhh.php 
<?php
include_once('pnum.class.php');
  if(Pnum::check($_POST['811115-1401'])) {
     echo "The personal number is correct";
  }

**Comment by engelfrost** [comment]
This project has no file called hhh.php, have you posted this report to the wrong project?

**Comment by gurre** [comment]
Sorry cannot use that info.
